// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/discord-v1/hooks.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Hooks_OnInit_FullMethodName              = "/discord_v1.Hooks/OnInit"
	Hooks_OnCreateMessage_FullMethodName     = "/discord_v1.Hooks/OnCreateMessage"
	Hooks_OnCreateInteraction_FullMethodName = "/discord_v1.Hooks/OnCreateInteraction"
	Hooks_OnEvent_FullMethodName             = "/discord_v1.Hooks/OnEvent"
)

// HooksClient is the client API for Hooks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HooksClient interface {
	// Runtime -> Module
	OnInit(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InitResponse, error)
	OnCreateMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	OnCreateInteraction(ctx context.Context, in *OnCreateInteractionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	OnEvent(ctx context.Context, in *OnEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type hooksClient struct {
	cc grpc.ClientConnInterface
}

func NewHooksClient(cc grpc.ClientConnInterface) HooksClient {
	return &hooksClient{cc}
}

func (c *hooksClient) OnInit(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InitResponse, error) {
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, Hooks_OnInit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hooksClient) OnCreateMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hooks_OnCreateMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hooksClient) OnCreateInteraction(ctx context.Context, in *OnCreateInteractionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hooks_OnCreateInteraction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hooksClient) OnEvent(ctx context.Context, in *OnEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hooks_OnEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HooksServer is the server API for Hooks service.
// All implementations should embed UnimplementedHooksServer
// for forward compatibility
type HooksServer interface {
	// Runtime -> Module
	OnInit(context.Context, *emptypb.Empty) (*InitResponse, error)
	OnCreateMessage(context.Context, *ChatMessage) (*emptypb.Empty, error)
	OnCreateInteraction(context.Context, *OnCreateInteractionRequest) (*emptypb.Empty, error)
	OnEvent(context.Context, *OnEventRequest) (*emptypb.Empty, error)
}

// UnimplementedHooksServer should be embedded to have forward compatible implementations.
type UnimplementedHooksServer struct {
}

func (UnimplementedHooksServer) OnInit(context.Context, *emptypb.Empty) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnInit not implemented")
}
func (UnimplementedHooksServer) OnCreateMessage(context.Context, *ChatMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnCreateMessage not implemented")
}
func (UnimplementedHooksServer) OnCreateInteraction(context.Context, *OnCreateInteractionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnCreateInteraction not implemented")
}
func (UnimplementedHooksServer) OnEvent(context.Context, *OnEventRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnEvent not implemented")
}

// UnsafeHooksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HooksServer will
// result in compilation errors.
type UnsafeHooksServer interface {
	mustEmbedUnimplementedHooksServer()
}

func RegisterHooksServer(s grpc.ServiceRegistrar, srv HooksServer) {
	s.RegisterService(&Hooks_ServiceDesc, srv)
}

func _Hooks_OnInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServer).OnInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hooks_OnInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServer).OnInit(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hooks_OnCreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServer).OnCreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hooks_OnCreateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServer).OnCreateMessage(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hooks_OnCreateInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnCreateInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServer).OnCreateInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hooks_OnCreateInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServer).OnCreateInteraction(ctx, req.(*OnCreateInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hooks_OnEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServer).OnEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hooks_OnEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServer).OnEvent(ctx, req.(*OnEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hooks_ServiceDesc is the grpc.ServiceDesc for Hooks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hooks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discord_v1.Hooks",
	HandlerType: (*HooksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnInit",
			Handler:    _Hooks_OnInit_Handler,
		},
		{
			MethodName: "OnCreateMessage",
			Handler:    _Hooks_OnCreateMessage_Handler,
		},
		{
			MethodName: "OnCreateInteraction",
			Handler:    _Hooks_OnCreateInteraction_Handler,
		},
		{
			MethodName: "OnEvent",
			Handler:    _Hooks_OnEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discord-v1/hooks.proto",
}
