// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: discord-v1/helper.proto

package discord_v1

import (
	_ "github.com/thirdscam/chatanium-flexmodule/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_discord_v1_helper_proto protoreflect.FileDescriptor

const file_discord_v1_helper_proto_rawDesc = "" +
	"\n" +
	"\x17discord-v1/helper.proto\x12\n" +
	"discord_v1\x1a\fcommon.proto\x1a\x1adiscord-v1/discordgo.proto2\b\n" +
	"\x06HelperB<Z:github.com/thirdscam/chatanium-flexmodule/proto/discord-v1b\x06proto3"

var file_discord_v1_helper_proto_goTypes = []any{}
var file_discord_v1_helper_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_discord_v1_helper_proto_init() }
func file_discord_v1_helper_proto_init() {
	if File_discord_v1_helper_proto != nil {
		return
	}
	file_discord_v1_discordgo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discord_v1_helper_proto_rawDesc), len(file_discord_v1_helper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discord_v1_helper_proto_goTypes,
		DependencyIndexes: file_discord_v1_helper_proto_depIdxs,
	}.Build()
	File_discord_v1_helper_proto = out.File
	file_discord_v1_helper_proto_goTypes = nil
	file_discord_v1_helper_proto_depIdxs = nil
}
