// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: discord-v1/helper.proto

package discord_v1

import (
	proto "github.com/thirdscam/chatanium-flexmodule/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId       string                 `protobuf:"bytes,2,opt,name=channelId,proto3" json:"channelId,omitempty"`
	GuildId         string                 `protobuf:"bytes,3,opt,name=guildId,proto3" json:"guildId,omitempty"`
	Content         string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EditedTimestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=edited_timestamp,json=editedTimestamp,proto3,oneof" json:"edited_timestamp,omitempty"`
	MentionRoles    []string               `protobuf:"bytes,7,rep,name=MentionRoles,proto3" json:"MentionRoles,omitempty"`
	Tts             bool                   `protobuf:"varint,8,opt,name=tts,proto3" json:"tts,omitempty"`
	MentionEveryone bool                   `protobuf:"varint,9,opt,name=mention_everyone,json=mentionEveryone,proto3" json:"mention_everyone,omitempty"`
	MessageFlags    int32                  `protobuf:"varint,10,opt,name=message_flags,json=messageFlags,proto3" json:"message_flags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_discord_v1_helper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_helper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_discord_v1_helper_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChatMessage) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ChatMessage) GetEditedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedTimestamp
	}
	return nil
}

func (x *ChatMessage) GetMentionRoles() []string {
	if x != nil {
		return x.MentionRoles
	}
	return nil
}

func (x *ChatMessage) GetTts() bool {
	if x != nil {
		return x.Tts
	}
	return false
}

func (x *ChatMessage) GetMentionEveryone() bool {
	if x != nil {
		return x.MentionEveryone
	}
	return false
}

func (x *ChatMessage) GetMessageFlags() int32 {
	if x != nil {
		return x.MessageFlags
	}
	return 0
}

type ChatIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatIdResponse) Reset() {
	*x = ChatIdResponse{}
	mi := &file_discord_v1_helper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatIdResponse) ProtoMessage() {}

func (x *ChatIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_helper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatIdResponse.ProtoReflect.Descriptor instead.
func (*ChatIdResponse) Descriptor() ([]byte, []int) {
	return file_discord_v1_helper_proto_rawDescGZIP(), []int{1}
}

func (x *ChatIdResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guildId,proto3" json:"guildId,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channelId,proto3" json:"channelId,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_discord_v1_helper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_helper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_discord_v1_helper_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ChatResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResponseInteractionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guildId,proto3" json:"guildId,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseInteractionRequest) Reset() {
	*x = ResponseInteractionRequest{}
	mi := &file_discord_v1_helper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseInteractionRequest) ProtoMessage() {}

func (x *ResponseInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_helper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseInteractionRequest.ProtoReflect.Descriptor instead.
func (*ResponseInteractionRequest) Descriptor() ([]byte, []int) {
	return file_discord_v1_helper_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseInteractionRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ResponseInteractionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EditInteractionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId string                 `protobuf:"bytes,1,opt,name=interactionId,proto3" json:"interactionId,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditInteractionRequest) Reset() {
	*x = EditInteractionRequest{}
	mi := &file_discord_v1_helper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditInteractionRequest) ProtoMessage() {}

func (x *EditInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_helper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditInteractionRequest.ProtoReflect.Descriptor instead.
func (*EditInteractionRequest) Descriptor() ([]byte, []int) {
	return file_discord_v1_helper_proto_rawDescGZIP(), []int{4}
}

func (x *EditInteractionRequest) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *EditInteractionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_discord_v1_helper_proto protoreflect.FileDescriptor

const file_discord_v1_helper_proto_rawDesc = "" +
	"\n" +
	"\x17discord-v1/helper.proto\x12\n" +
	"discord_v1\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x03\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tchannelId\x18\x02 \x01(\tR\tchannelId\x12\x18\n" +
	"\aguildId\x18\x03 \x01(\tR\aguildId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12J\n" +
	"\x10edited_timestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0feditedTimestamp\x88\x01\x01\x12\"\n" +
	"\fMentionRoles\x18\a \x03(\tR\fMentionRoles\x12\x10\n" +
	"\x03tts\x18\b \x01(\bR\x03tts\x12)\n" +
	"\x10mention_everyone\x18\t \x01(\bR\x0fmentionEveryone\x12#\n" +
	"\rmessage_flags\x18\n" +
	" \x01(\x05R\fmessageFlagsB\x13\n" +
	"\x11_edited_timestamp\"(\n" +
	"\x0eChatIdResponse\x12\x16\n" +
	"\x06chatId\x18\x01 \x01(\tR\x06chatId\"`\n" +
	"\fChatResponse\x12\x18\n" +
	"\aguildId\x18\x01 \x01(\tR\aguildId\x12\x1c\n" +
	"\tchannelId\x18\x02 \x01(\tR\tchannelId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"P\n" +
	"\x1aResponseInteractionRequest\x12\x18\n" +
	"\aguildId\x18\x01 \x01(\tR\aguildId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"X\n" +
	"\x16EditInteractionRequest\x12$\n" +
	"\rinteractionId\x18\x01 \x01(\tR\rinteractionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa8\x02\n" +
	"\x06Helper\x12F\n" +
	"\x0fResponseMessage\x12\x17.discord_v1.ChatMessage\x1a\x1a.discord_v1.ChatIdResponse\x12Y\n" +
	"\x13ResponseInteraction\x12&.discord_v1.ResponseInteractionRequest\x1a\x1a.discord_v1.ChatIdResponse\x125\n" +
	"\vEditMessage\x12\x17.discord_v1.ChatMessage\x1a\r.common.Empty\x12D\n" +
	"\x0fEditInteraction\x12\".discord_v1.EditInteractionRequest\x1a\r.common.EmptyB<Z:github.com/thirdscam/chatanium-flexmodule/proto/discord-v1b\x06proto3"

var (
	file_discord_v1_helper_proto_rawDescOnce sync.Once
	file_discord_v1_helper_proto_rawDescData []byte
)

func file_discord_v1_helper_proto_rawDescGZIP() []byte {
	file_discord_v1_helper_proto_rawDescOnce.Do(func() {
		file_discord_v1_helper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discord_v1_helper_proto_rawDesc), len(file_discord_v1_helper_proto_rawDesc)))
	})
	return file_discord_v1_helper_proto_rawDescData
}

var file_discord_v1_helper_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_discord_v1_helper_proto_goTypes = []any{
	(*ChatMessage)(nil),                // 0: discord_v1.ChatMessage
	(*ChatIdResponse)(nil),             // 1: discord_v1.ChatIdResponse
	(*ChatResponse)(nil),               // 2: discord_v1.ChatResponse
	(*ResponseInteractionRequest)(nil), // 3: discord_v1.ResponseInteractionRequest
	(*EditInteractionRequest)(nil),     // 4: discord_v1.EditInteractionRequest
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
	(*proto.Empty)(nil),                // 6: common.Empty
}
var file_discord_v1_helper_proto_depIdxs = []int32{
	5, // 0: discord_v1.ChatMessage.timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: discord_v1.ChatMessage.edited_timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: discord_v1.Helper.ResponseMessage:input_type -> discord_v1.ChatMessage
	3, // 3: discord_v1.Helper.ResponseInteraction:input_type -> discord_v1.ResponseInteractionRequest
	0, // 4: discord_v1.Helper.EditMessage:input_type -> discord_v1.ChatMessage
	4, // 5: discord_v1.Helper.EditInteraction:input_type -> discord_v1.EditInteractionRequest
	1, // 6: discord_v1.Helper.ResponseMessage:output_type -> discord_v1.ChatIdResponse
	1, // 7: discord_v1.Helper.ResponseInteraction:output_type -> discord_v1.ChatIdResponse
	6, // 8: discord_v1.Helper.EditMessage:output_type -> common.Empty
	6, // 9: discord_v1.Helper.EditInteraction:output_type -> common.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_discord_v1_helper_proto_init() }
func file_discord_v1_helper_proto_init() {
	if File_discord_v1_helper_proto != nil {
		return
	}
	file_discord_v1_helper_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discord_v1_helper_proto_rawDesc), len(file_discord_v1_helper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discord_v1_helper_proto_goTypes,
		DependencyIndexes: file_discord_v1_helper_proto_depIdxs,
		MessageInfos:      file_discord_v1_helper_proto_msgTypes,
	}.Build()
	File_discord_v1_helper_proto = out.File
	file_discord_v1_helper_proto_goTypes = nil
	file_discord_v1_helper_proto_depIdxs = nil
}
