// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: discord-v1/helper.proto

package discord_v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// HelperClient is the client API for Helper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelperClient interface {
}

type helperClient struct {
	cc grpc.ClientConnInterface
}

func NewHelperClient(cc grpc.ClientConnInterface) HelperClient {
	return &helperClient{cc}
}

// HelperServer is the server API for Helper service.
// All implementations should embed UnimplementedHelperServer
// for forward compatibility
type HelperServer interface {
}

// UnimplementedHelperServer should be embedded to have forward compatible implementations.
type UnimplementedHelperServer struct {
}

// UnsafeHelperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelperServer will
// result in compilation errors.
type UnsafeHelperServer interface {
	mustEmbedUnimplementedHelperServer()
}

func RegisterHelperServer(s grpc.ServiceRegistrar, srv HelperServer) {
	s.RegisterService(&Helper_ServiceDesc, srv)
}

// Helper_ServiceDesc is the grpc.ServiceDesc for Helper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Helper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discord_v1.Helper",
	HandlerType: (*HelperServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "discord-v1/helper.proto",
}
