// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: discord-v1/voice.proto

package discord_v1

import (
	proto "github.com/thirdscam/chatanium-flexmodule/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Voice join request
type VoiceJoinRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	GuildId   string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ChannelId string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Mute      bool                   `protobuf:"varint,3,opt,name=mute,proto3" json:"mute,omitempty"`
	Deaf      bool                   `protobuf:"varint,4,opt,name=deaf,proto3" json:"deaf,omitempty"`
	// Optional settings
	Priority      int32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                       // Default priority (0 = normal)
	BufferSize    int32 `protobuf:"varint,6,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"` // Receive buffer size (default 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceJoinRequest) Reset() {
	*x = VoiceJoinRequest{}
	mi := &file_discord_v1_voice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceJoinRequest) ProtoMessage() {}

func (x *VoiceJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_voice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceJoinRequest.ProtoReflect.Descriptor instead.
func (*VoiceJoinRequest) Descriptor() ([]byte, []int) {
	return file_discord_v1_voice_proto_rawDescGZIP(), []int{0}
}

func (x *VoiceJoinRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *VoiceJoinRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *VoiceJoinRequest) GetMute() bool {
	if x != nil {
		return x.Mute
	}
	return false
}

func (x *VoiceJoinRequest) GetDeaf() bool {
	if x != nil {
		return x.Deaf
	}
	return false
}

func (x *VoiceJoinRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *VoiceJoinRequest) GetBufferSize() int32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

// Voice join response
type VoiceJoinResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"` // Subscription session ID
	GuildId      string                 `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ChannelId    string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Ready        bool                   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	// Queue information
	QueueLength       int32 `protobuf:"varint,5,opt,name=queue_length,json=queueLength,proto3" json:"queue_length,omitempty"`                   // Current queue length
	ActiveSubscribers int32 `protobuf:"varint,6,opt,name=active_subscribers,json=activeSubscribers,proto3" json:"active_subscribers,omitempty"` // Active subscriber count
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VoiceJoinResponse) Reset() {
	*x = VoiceJoinResponse{}
	mi := &file_discord_v1_voice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceJoinResponse) ProtoMessage() {}

func (x *VoiceJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_voice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceJoinResponse.ProtoReflect.Descriptor instead.
func (*VoiceJoinResponse) Descriptor() ([]byte, []int) {
	return file_discord_v1_voice_proto_rawDescGZIP(), []int{1}
}

func (x *VoiceJoinResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *VoiceJoinResponse) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *VoiceJoinResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *VoiceJoinResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *VoiceJoinResponse) GetQueueLength() int32 {
	if x != nil {
		return x.QueueLength
	}
	return 0
}

func (x *VoiceJoinResponse) GetActiveSubscribers() int32 {
	if x != nil {
		return x.ActiveSubscribers
	}
	return 0
}

// Voice packet
type VoicePacket struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	OpusData     []byte                 `protobuf:"bytes,2,opt,name=opus_data,json=opusData,proto3" json:"opus_data,omitempty"`
	// Configurable when sending
	Priority  int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`                    // Task priority (-10 ~ 10)
	TimeoutMs int64 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // Timeout in milliseconds
	// Included when receiving
	Ssrc          uint32 `protobuf:"varint,5,opt,name=ssrc,proto3" json:"ssrc,omitempty"`           // Sender SSRC
	Sequence      uint32 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`   // Packet sequence
	Timestamp     uint32 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RTP timestamp
	Type          []byte `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`            // Packet type (special markers)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoicePacket) Reset() {
	*x = VoicePacket{}
	mi := &file_discord_v1_voice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoicePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoicePacket) ProtoMessage() {}

func (x *VoicePacket) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_voice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoicePacket.ProtoReflect.Descriptor instead.
func (*VoicePacket) Descriptor() ([]byte, []int) {
	return file_discord_v1_voice_proto_rawDescGZIP(), []int{2}
}

func (x *VoicePacket) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *VoicePacket) GetOpusData() []byte {
	if x != nil {
		return x.OpusData
	}
	return nil
}

func (x *VoicePacket) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *VoicePacket) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *VoicePacket) GetSsrc() uint32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

func (x *VoicePacket) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *VoicePacket) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *VoicePacket) GetType() []byte {
	if x != nil {
		return x.Type
	}
	return nil
}

// Voice leave request
type VoiceLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceLeaveRequest) Reset() {
	*x = VoiceLeaveRequest{}
	mi := &file_discord_v1_voice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceLeaveRequest) ProtoMessage() {}

func (x *VoiceLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_voice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceLeaveRequest.ProtoReflect.Descriptor instead.
func (*VoiceLeaveRequest) Descriptor() ([]byte, []int) {
	return file_discord_v1_voice_proto_rawDescGZIP(), []int{3}
}

func (x *VoiceLeaveRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// Voice speaking request
type VoiceSpeakingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Speaking      bool                   `protobuf:"varint,2,opt,name=speaking,proto3" json:"speaking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceSpeakingRequest) Reset() {
	*x = VoiceSpeakingRequest{}
	mi := &file_discord_v1_voice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceSpeakingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceSpeakingRequest) ProtoMessage() {}

func (x *VoiceSpeakingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_voice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceSpeakingRequest.ProtoReflect.Descriptor instead.
func (*VoiceSpeakingRequest) Descriptor() ([]byte, []int) {
	return file_discord_v1_voice_proto_rawDescGZIP(), []int{4}
}

func (x *VoiceSpeakingRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *VoiceSpeakingRequest) GetSpeaking() bool {
	if x != nil {
		return x.Speaking
	}
	return false
}

// Queue status request
type QueueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatusRequest) Reset() {
	*x = QueueStatusRequest{}
	mi := &file_discord_v1_voice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusRequest) ProtoMessage() {}

func (x *QueueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_voice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusRequest.ProtoReflect.Descriptor instead.
func (*QueueStatusRequest) Descriptor() ([]byte, []int) {
	return file_discord_v1_voice_proto_rawDescGZIP(), []int{5}
}

func (x *QueueStatusRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

// Queue status response
type QueueStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueueLength       int32                  `protobuf:"varint,1,opt,name=queue_length,json=queueLength,proto3" json:"queue_length,omitempty"`
	ActiveSubscribers int32                  `protobuf:"varint,2,opt,name=active_subscribers,json=activeSubscribers,proto3" json:"active_subscribers,omitempty"`
	ModuleStats       []*ModuleStats         `protobuf:"bytes,3,rep,name=module_stats,json=moduleStats,proto3" json:"module_stats,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueueStatusResponse) Reset() {
	*x = QueueStatusResponse{}
	mi := &file_discord_v1_voice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusResponse) ProtoMessage() {}

func (x *QueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_voice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusResponse.ProtoReflect.Descriptor instead.
func (*QueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_discord_v1_voice_proto_rawDescGZIP(), []int{6}
}

func (x *QueueStatusResponse) GetQueueLength() int32 {
	if x != nil {
		return x.QueueLength
	}
	return 0
}

func (x *QueueStatusResponse) GetActiveSubscribers() int32 {
	if x != nil {
		return x.ActiveSubscribers
	}
	return 0
}

func (x *QueueStatusResponse) GetModuleStats() []*ModuleStats {
	if x != nil {
		return x.ModuleStats
	}
	return nil
}

// Module statistics
type ModuleStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModuleId       string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	TasksSubmitted uint64                 `protobuf:"varint,2,opt,name=tasks_submitted,json=tasksSubmitted,proto3" json:"tasks_submitted,omitempty"`
	TasksProcessed uint64                 `protobuf:"varint,3,opt,name=tasks_processed,json=tasksProcessed,proto3" json:"tasks_processed,omitempty"`
	BytesSent      uint64                 `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived  uint64                 `protobuf:"varint,5,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModuleStats) Reset() {
	*x = ModuleStats{}
	mi := &file_discord_v1_voice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStats) ProtoMessage() {}

func (x *ModuleStats) ProtoReflect() protoreflect.Message {
	mi := &file_discord_v1_voice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStats.ProtoReflect.Descriptor instead.
func (*ModuleStats) Descriptor() ([]byte, []int) {
	return file_discord_v1_voice_proto_rawDescGZIP(), []int{7}
}

func (x *ModuleStats) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleStats) GetTasksSubmitted() uint64 {
	if x != nil {
		return x.TasksSubmitted
	}
	return 0
}

func (x *ModuleStats) GetTasksProcessed() uint64 {
	if x != nil {
		return x.TasksProcessed
	}
	return 0
}

func (x *ModuleStats) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *ModuleStats) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

var File_discord_v1_voice_proto protoreflect.FileDescriptor

const file_discord_v1_voice_proto_rawDesc = "" +
	"\n" +
	"\x16discord-v1/voice.proto\x12\n" +
	"discord_v1\x1a\fcommon.proto\"\xb1\x01\n" +
	"\x10VoiceJoinRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04mute\x18\x03 \x01(\bR\x04mute\x12\x12\n" +
	"\x04deaf\x18\x04 \x01(\bR\x04deaf\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vbuffer_size\x18\x06 \x01(\x05R\n" +
	"bufferSize\"\xda\x01\n" +
	"\x11VoiceJoinResponse\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x19\n" +
	"\bguild_id\x18\x02 \x01(\tR\aguildId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12!\n" +
	"\fqueue_length\x18\x05 \x01(\x05R\vqueueLength\x12-\n" +
	"\x12active_subscribers\x18\x06 \x01(\x05R\x11activeSubscribers\"\xec\x01\n" +
	"\vVoicePacket\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1b\n" +
	"\topus_data\x18\x02 \x01(\fR\bopusData\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\x12\x12\n" +
	"\x04ssrc\x18\x05 \x01(\rR\x04ssrc\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\rR\bsequence\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\rR\ttimestamp\x12\x12\n" +
	"\x04type\x18\b \x01(\fR\x04type\"8\n" +
	"\x11VoiceLeaveRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"W\n" +
	"\x14VoiceSpeakingRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1a\n" +
	"\bspeaking\x18\x02 \x01(\bR\bspeaking\"/\n" +
	"\x12QueueStatusRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\"\xa3\x01\n" +
	"\x13QueueStatusResponse\x12!\n" +
	"\fqueue_length\x18\x01 \x01(\x05R\vqueueLength\x12-\n" +
	"\x12active_subscribers\x18\x02 \x01(\x05R\x11activeSubscribers\x12:\n" +
	"\fmodule_stats\x18\x03 \x03(\v2\x17.discord_v1.ModuleStatsR\vmoduleStats\"\xc2\x01\n" +
	"\vModuleStats\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12'\n" +
	"\x0ftasks_submitted\x18\x02 \x01(\x04R\x0etasksSubmitted\x12'\n" +
	"\x0ftasks_processed\x18\x03 \x01(\x04R\x0etasksProcessed\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x05 \x01(\x04R\rbytesReceived2\xed\x02\n" +
	"\vVoiceStream\x12H\n" +
	"\tVoiceJoin\x12\x1c.discord_v1.VoiceJoinRequest\x1a\x1d.discord_v1.VoiceJoinResponse\x12C\n" +
	"\vVoiceStream\x12\x17.discord_v1.VoicePacket\x1a\x17.discord_v1.VoicePacket(\x010\x01\x12:\n" +
	"\n" +
	"VoiceLeave\x12\x1d.discord_v1.VoiceLeaveRequest\x1a\r.common.Empty\x12@\n" +
	"\rVoiceSpeaking\x12 .discord_v1.VoiceSpeakingRequest\x1a\r.common.Empty\x12Q\n" +
	"\x0eGetQueueStatus\x12\x1e.discord_v1.QueueStatusRequest\x1a\x1f.discord_v1.QueueStatusResponseB<Z:github.com/thirdscam/chatanium-flexmodule/proto/discord-v1b\x06proto3"

var (
	file_discord_v1_voice_proto_rawDescOnce sync.Once
	file_discord_v1_voice_proto_rawDescData []byte
)

func file_discord_v1_voice_proto_rawDescGZIP() []byte {
	file_discord_v1_voice_proto_rawDescOnce.Do(func() {
		file_discord_v1_voice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discord_v1_voice_proto_rawDesc), len(file_discord_v1_voice_proto_rawDesc)))
	})
	return file_discord_v1_voice_proto_rawDescData
}

var file_discord_v1_voice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_discord_v1_voice_proto_goTypes = []any{
	(*VoiceJoinRequest)(nil),     // 0: discord_v1.VoiceJoinRequest
	(*VoiceJoinResponse)(nil),    // 1: discord_v1.VoiceJoinResponse
	(*VoicePacket)(nil),          // 2: discord_v1.VoicePacket
	(*VoiceLeaveRequest)(nil),    // 3: discord_v1.VoiceLeaveRequest
	(*VoiceSpeakingRequest)(nil), // 4: discord_v1.VoiceSpeakingRequest
	(*QueueStatusRequest)(nil),   // 5: discord_v1.QueueStatusRequest
	(*QueueStatusResponse)(nil),  // 6: discord_v1.QueueStatusResponse
	(*ModuleStats)(nil),          // 7: discord_v1.ModuleStats
	(*proto.Empty)(nil),          // 8: common.Empty
}
var file_discord_v1_voice_proto_depIdxs = []int32{
	7, // 0: discord_v1.QueueStatusResponse.module_stats:type_name -> discord_v1.ModuleStats
	0, // 1: discord_v1.VoiceStream.VoiceJoin:input_type -> discord_v1.VoiceJoinRequest
	2, // 2: discord_v1.VoiceStream.VoiceStream:input_type -> discord_v1.VoicePacket
	3, // 3: discord_v1.VoiceStream.VoiceLeave:input_type -> discord_v1.VoiceLeaveRequest
	4, // 4: discord_v1.VoiceStream.VoiceSpeaking:input_type -> discord_v1.VoiceSpeakingRequest
	5, // 5: discord_v1.VoiceStream.GetQueueStatus:input_type -> discord_v1.QueueStatusRequest
	1, // 6: discord_v1.VoiceStream.VoiceJoin:output_type -> discord_v1.VoiceJoinResponse
	2, // 7: discord_v1.VoiceStream.VoiceStream:output_type -> discord_v1.VoicePacket
	8, // 8: discord_v1.VoiceStream.VoiceLeave:output_type -> common.Empty
	8, // 9: discord_v1.VoiceStream.VoiceSpeaking:output_type -> common.Empty
	6, // 10: discord_v1.VoiceStream.GetQueueStatus:output_type -> discord_v1.QueueStatusResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_discord_v1_voice_proto_init() }
func file_discord_v1_voice_proto_init() {
	if File_discord_v1_voice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discord_v1_voice_proto_rawDesc), len(file_discord_v1_voice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discord_v1_voice_proto_goTypes,
		DependencyIndexes: file_discord_v1_voice_proto_depIdxs,
		MessageInfos:      file_discord_v1_voice_proto_msgTypes,
	}.Build()
	File_discord_v1_voice_proto = out.File
	file_discord_v1_voice_proto_goTypes = nil
	file_discord_v1_voice_proto_depIdxs = nil
}
