// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: discord-v1/voice.proto

package discord_v1

import (
	context "context"
	proto "github.com/thirdscam/chatanium-flexmodule/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VoiceStream_VoiceJoin_FullMethodName      = "/discord_v1.VoiceStream/VoiceJoin"
	VoiceStream_VoiceStream_FullMethodName    = "/discord_v1.VoiceStream/VoiceStream"
	VoiceStream_VoiceLeave_FullMethodName     = "/discord_v1.VoiceStream/VoiceLeave"
	VoiceStream_VoiceSpeaking_FullMethodName  = "/discord_v1.VoiceStream/VoiceSpeaking"
	VoiceStream_GetQueueStatus_FullMethodName = "/discord_v1.VoiceStream/GetQueueStatus"
)

// VoiceStreamClient is the client API for VoiceStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceStreamClient interface {
	// Join a voice channel
	VoiceJoin(ctx context.Context, in *VoiceJoinRequest, opts ...grpc.CallOption) (*VoiceJoinResponse, error)
	// Bidirectional voice stream (queue-based send + broadcast receive)
	VoiceStream(ctx context.Context, opts ...grpc.CallOption) (VoiceStream_VoiceStreamClient, error)
	// Leave voice channel
	VoiceLeave(ctx context.Context, in *VoiceLeaveRequest, opts ...grpc.CallOption) (*proto.Empty, error)
	// Set speaking state
	VoiceSpeaking(ctx context.Context, in *VoiceSpeakingRequest, opts ...grpc.CallOption) (*proto.Empty, error)
	// Get queue status (for debugging)
	GetQueueStatus(ctx context.Context, in *QueueStatusRequest, opts ...grpc.CallOption) (*QueueStatusResponse, error)
}

type voiceStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceStreamClient(cc grpc.ClientConnInterface) VoiceStreamClient {
	return &voiceStreamClient{cc}
}

func (c *voiceStreamClient) VoiceJoin(ctx context.Context, in *VoiceJoinRequest, opts ...grpc.CallOption) (*VoiceJoinResponse, error) {
	out := new(VoiceJoinResponse)
	err := c.cc.Invoke(ctx, VoiceStream_VoiceJoin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceStreamClient) VoiceStream(ctx context.Context, opts ...grpc.CallOption) (VoiceStream_VoiceStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &VoiceStream_ServiceDesc.Streams[0], VoiceStream_VoiceStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &voiceStreamVoiceStreamClient{stream}
	return x, nil
}

type VoiceStream_VoiceStreamClient interface {
	Send(*VoicePacket) error
	Recv() (*VoicePacket, error)
	grpc.ClientStream
}

type voiceStreamVoiceStreamClient struct {
	grpc.ClientStream
}

func (x *voiceStreamVoiceStreamClient) Send(m *VoicePacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *voiceStreamVoiceStreamClient) Recv() (*VoicePacket, error) {
	m := new(VoicePacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *voiceStreamClient) VoiceLeave(ctx context.Context, in *VoiceLeaveRequest, opts ...grpc.CallOption) (*proto.Empty, error) {
	out := new(proto.Empty)
	err := c.cc.Invoke(ctx, VoiceStream_VoiceLeave_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceStreamClient) VoiceSpeaking(ctx context.Context, in *VoiceSpeakingRequest, opts ...grpc.CallOption) (*proto.Empty, error) {
	out := new(proto.Empty)
	err := c.cc.Invoke(ctx, VoiceStream_VoiceSpeaking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceStreamClient) GetQueueStatus(ctx context.Context, in *QueueStatusRequest, opts ...grpc.CallOption) (*QueueStatusResponse, error) {
	out := new(QueueStatusResponse)
	err := c.cc.Invoke(ctx, VoiceStream_GetQueueStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoiceStreamServer is the server API for VoiceStream service.
// All implementations should embed UnimplementedVoiceStreamServer
// for forward compatibility
type VoiceStreamServer interface {
	// Join a voice channel
	VoiceJoin(context.Context, *VoiceJoinRequest) (*VoiceJoinResponse, error)
	// Bidirectional voice stream (queue-based send + broadcast receive)
	VoiceStream(VoiceStream_VoiceStreamServer) error
	// Leave voice channel
	VoiceLeave(context.Context, *VoiceLeaveRequest) (*proto.Empty, error)
	// Set speaking state
	VoiceSpeaking(context.Context, *VoiceSpeakingRequest) (*proto.Empty, error)
	// Get queue status (for debugging)
	GetQueueStatus(context.Context, *QueueStatusRequest) (*QueueStatusResponse, error)
}

// UnimplementedVoiceStreamServer should be embedded to have forward compatible implementations.
type UnimplementedVoiceStreamServer struct {
}

func (UnimplementedVoiceStreamServer) VoiceJoin(context.Context, *VoiceJoinRequest) (*VoiceJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoiceJoin not implemented")
}
func (UnimplementedVoiceStreamServer) VoiceStream(VoiceStream_VoiceStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method VoiceStream not implemented")
}
func (UnimplementedVoiceStreamServer) VoiceLeave(context.Context, *VoiceLeaveRequest) (*proto.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoiceLeave not implemented")
}
func (UnimplementedVoiceStreamServer) VoiceSpeaking(context.Context, *VoiceSpeakingRequest) (*proto.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoiceSpeaking not implemented")
}
func (UnimplementedVoiceStreamServer) GetQueueStatus(context.Context, *QueueStatusRequest) (*QueueStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueueStatus not implemented")
}

// UnsafeVoiceStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceStreamServer will
// result in compilation errors.
type UnsafeVoiceStreamServer interface {
	mustEmbedUnimplementedVoiceStreamServer()
}

func RegisterVoiceStreamServer(s grpc.ServiceRegistrar, srv VoiceStreamServer) {
	s.RegisterService(&VoiceStream_ServiceDesc, srv)
}

func _VoiceStream_VoiceJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoiceJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceStreamServer).VoiceJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceStream_VoiceJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceStreamServer).VoiceJoin(ctx, req.(*VoiceJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceStream_VoiceStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VoiceStreamServer).VoiceStream(&voiceStreamVoiceStreamServer{stream})
}

type VoiceStream_VoiceStreamServer interface {
	Send(*VoicePacket) error
	Recv() (*VoicePacket, error)
	grpc.ServerStream
}

type voiceStreamVoiceStreamServer struct {
	grpc.ServerStream
}

func (x *voiceStreamVoiceStreamServer) Send(m *VoicePacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *voiceStreamVoiceStreamServer) Recv() (*VoicePacket, error) {
	m := new(VoicePacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VoiceStream_VoiceLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoiceLeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceStreamServer).VoiceLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceStream_VoiceLeave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceStreamServer).VoiceLeave(ctx, req.(*VoiceLeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceStream_VoiceSpeaking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoiceSpeakingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceStreamServer).VoiceSpeaking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceStream_VoiceSpeaking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceStreamServer).VoiceSpeaking(ctx, req.(*VoiceSpeakingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceStream_GetQueueStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceStreamServer).GetQueueStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceStream_GetQueueStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceStreamServer).GetQueueStatus(ctx, req.(*QueueStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoiceStream_ServiceDesc is the grpc.ServiceDesc for VoiceStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discord_v1.VoiceStream",
	HandlerType: (*VoiceStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VoiceJoin",
			Handler:    _VoiceStream_VoiceJoin_Handler,
		},
		{
			MethodName: "VoiceLeave",
			Handler:    _VoiceStream_VoiceLeave_Handler,
		},
		{
			MethodName: "VoiceSpeaking",
			Handler:    _VoiceStream_VoiceSpeaking_Handler,
		},
		{
			MethodName: "GetQueueStatus",
			Handler:    _VoiceStream_GetQueueStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VoiceStream",
			Handler:       _VoiceStream_VoiceStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "discord-v1/voice.proto",
}
