// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core-v1/helper.proto

package core_v1

import (
	proto "github.com/thirdscam/chatanium-flexmodule/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_core_v1_helper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_helper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_helper_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_core_v1_helper_proto protoreflect.FileDescriptor

const file_core_v1_helper_proto_rawDesc = "" +
	"\n" +
	"\x14core-v1/helper.proto\x12\acore_v1\x1a\fcommon.proto\"\x8e\x01\n" +
	"\x11GetConfigResponse\x12>\n" +
	"\x06config\x18\x03 \x03(\v2&.core_v1.GetConfigResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012@\n" +
	"\x06Helper\x126\n" +
	"\tGetConfig\x12\r.common.Empty\x1a\x1a.core_v1.GetConfigResponseB9Z7github.com/thirdscam/chatanium-flexmodule/proto/core-v1b\x06proto3"

var (
	file_core_v1_helper_proto_rawDescOnce sync.Once
	file_core_v1_helper_proto_rawDescData []byte
)

func file_core_v1_helper_proto_rawDescGZIP() []byte {
	file_core_v1_helper_proto_rawDescOnce.Do(func() {
		file_core_v1_helper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_helper_proto_rawDesc), len(file_core_v1_helper_proto_rawDesc)))
	})
	return file_core_v1_helper_proto_rawDescData
}

var file_core_v1_helper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_v1_helper_proto_goTypes = []any{
	(*GetConfigResponse)(nil), // 0: core_v1.GetConfigResponse
	nil,                       // 1: core_v1.GetConfigResponse.ConfigEntry
	(*proto.Empty)(nil),       // 2: common.Empty
}
var file_core_v1_helper_proto_depIdxs = []int32{
	1, // 0: core_v1.GetConfigResponse.config:type_name -> core_v1.GetConfigResponse.ConfigEntry
	2, // 1: core_v1.Helper.GetConfig:input_type -> common.Empty
	0, // 2: core_v1.Helper.GetConfig:output_type -> core_v1.GetConfigResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_v1_helper_proto_init() }
func file_core_v1_helper_proto_init() {
	if File_core_v1_helper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_helper_proto_rawDesc), len(file_core_v1_helper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_helper_proto_goTypes,
		DependencyIndexes: file_core_v1_helper_proto_depIdxs,
		MessageInfos:      file_core_v1_helper_proto_msgTypes,
	}.Build()
	File_core_v1_helper_proto = out.File
	file_core_v1_helper_proto_goTypes = nil
	file_core_v1_helper_proto_depIdxs = nil
}
