// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: core-v1/hook.proto

package core_v1

import (
	proto "github.com/thirdscam/chatanium-flexmodule/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Repository    string                 `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_core_v1_hook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_hook_proto_rawDescGZIP(), []int{0}
}

func (x *GetManifestResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetManifestResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetManifestResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GetManifestResponse) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *GetManifestResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReady       bool                   `protobuf:"varint,1,opt,name=isReady,proto3" json:"isReady,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_core_v1_hook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_hook_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type OnStageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnStageRequest) Reset() {
	*x = OnStageRequest{}
	mi := &file_core_v1_hook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnStageRequest) ProtoMessage() {}

func (x *OnStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnStageRequest.ProtoReflect.Descriptor instead.
func (*OnStageRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_hook_proto_rawDescGZIP(), []int{2}
}

func (x *OnStageRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

var File_core_v1_hook_proto protoreflect.FileDescriptor

const file_core_v1_hook_proto_rawDesc = "" +
	"\n" +
	"\x12core-v1/hook.proto\x12\acore_v1\x1a\fcommon.proto\"\x9d\x01\n" +
	"\x13GetManifestResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x1e\n" +
	"\n" +
	"repository\x18\x04 \x01(\tR\n" +
	"repository\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\"-\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\aisReady\x18\x01 \x01(\bR\aisReady\"&\n" +
	"\x0eOnStageRequest\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage2\xad\x01\n" +
	"\x04Hook\x12:\n" +
	"\vGetManifest\x12\r.common.Empty\x1a\x1c.core_v1.GetManifestResponse\x126\n" +
	"\tGetStatus\x12\r.common.Empty\x1a\x1a.core_v1.GetStatusResponse\x121\n" +
	"\aOnStage\x12\x17.core_v1.OnStageRequest\x1a\r.common.EmptyB9Z7github.com/thirdscam/chatanium-flexmodule/proto/core-v1b\x06proto3"

var (
	file_core_v1_hook_proto_rawDescOnce sync.Once
	file_core_v1_hook_proto_rawDescData []byte
)

func file_core_v1_hook_proto_rawDescGZIP() []byte {
	file_core_v1_hook_proto_rawDescOnce.Do(func() {
		file_core_v1_hook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_hook_proto_rawDesc), len(file_core_v1_hook_proto_rawDesc)))
	})
	return file_core_v1_hook_proto_rawDescData
}

var file_core_v1_hook_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_v1_hook_proto_goTypes = []any{
	(*GetManifestResponse)(nil), // 0: core_v1.GetManifestResponse
	(*GetStatusResponse)(nil),   // 1: core_v1.GetStatusResponse
	(*OnStageRequest)(nil),      // 2: core_v1.OnStageRequest
	(*proto.Empty)(nil),         // 3: common.Empty
}
var file_core_v1_hook_proto_depIdxs = []int32{
	3, // 0: core_v1.Hook.GetManifest:input_type -> common.Empty
	3, // 1: core_v1.Hook.GetStatus:input_type -> common.Empty
	2, // 2: core_v1.Hook.OnStage:input_type -> core_v1.OnStageRequest
	0, // 3: core_v1.Hook.GetManifest:output_type -> core_v1.GetManifestResponse
	1, // 4: core_v1.Hook.GetStatus:output_type -> core_v1.GetStatusResponse
	3, // 5: core_v1.Hook.OnStage:output_type -> common.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_v1_hook_proto_init() }
func file_core_v1_hook_proto_init() {
	if File_core_v1_hook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_hook_proto_rawDesc), len(file_core_v1_hook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_hook_proto_goTypes,
		DependencyIndexes: file_core_v1_hook_proto_depIdxs,
		MessageInfos:      file_core_v1_hook_proto_msgTypes,
	}.Build()
	File_core_v1_hook_proto = out.File
	file_core_v1_hook_proto_goTypes = nil
	file_core_v1_hook_proto_depIdxs = nil
}
